### PR TITLE
Refactor config

### PR DESCRIPTION
**Pull request by izik1**
This PR moves from `config.py` to Anki's json based config, with hopefully no real breakage. A lot of config settings were somewhat renamed, and the completely unused ones were removed.

The motivation behind this is that `config.py` gets reset on every release because either the user will be using master (in which case they have to copy over config.py) or they're using Anki web, in which case Anki would delete it upon updating. A secondary motivation is that this allows changing some of those settings without restarting Anki.

**NOTICE: THIS IS A BREAKING CHANGE AND USERS _WILL_ HAVE TO PUT IN SOME EFFORT IN ORDER TO UPGRADE** 

I say that, although, it's mostly just learning what the new names for settings are, which shouldn't be very hard, as they didn't change much. I have a map of which settings were renamed to what, which I can provide if need be.

I am willing to make changes to this if need be in order to get it merged, it's likely that some surrounding documentation in and out of the repository will have to change, and I am willing to assist with that.

### CODE REVIEW

**Comment by izik1** [comment]
* not directly related to the PR itself, hence being in a comment, but I decided to make this for myself before I realized I should probably try to get it merged, hence the lack of an issue as an RFC.

**Comment by shanrauf** [comment]
I'm not sure that merging all of this currently would be the best move, since not only would all documentation have to be updated in many different places (e.x Matt vs Japan recently updated his Morphman guide and created a new video to reflect the addon's exact state as of right now), but also all users would have to be educated about the new config names and functionality and what not.

Do you think there's a way to sync a user's config.py file with Anki's config (so that on addon updates, their settings are saved), but still keep the config.py there and edittable so that from the user's POV, there are no breaking changes and all documentation still holds up? (Because the big issue is config not syncing - I also agree that some config/variable names could be fixed, but that relates to what I mentioned up top about breaking issues, whereas syncing config.py w Anki's config would solve the bigger issue we're dealing with).

Lastly, there are some good stuff and bug fixes in this PR that I would be down to merge, but I can't because they're mixed with the config stuff which I already explained my thoughts on up top. Maybe create separate, smaller PR's with those smaller fixes you made, because I can accept those a lot faster.

Thanks!

**Comment by izik1** [comment]
> Do you think there's a way to sync a user's config.py file with Anki's config (so that on addon updates, their settings are saved), but still keep the config.py there and edittable so that from the user's POV, there are no breaking changes and all documentation still holds up?

Hmm, I think it's possible, perhaps by adding a default `false` bool "useNewConfig" to `config.json`, where, when false, basically redirects to `config.py`, while silently copying changes to `config.py` onto the new `config.json`. Going the other way might be harder (syncing from config.json to config.py), but, after solving that, perhaps add upgrade instructions somewhere to set `useNewConfig` to true while upgrading, and then back to `false` again after if you wish to keep using old behavour?

Basically, the high level explanation of what I described would be: There would be two config modes: default config.py (copying over changes to config.json as a kind of secondary), and default config.json, which does the opposite. The upgrade path I'd probably use is: introduce new system (defaulting to old) _without deprecating the old system_, officially deprecate old system (still defaulting to old) and encouraging users to update to the new system, change default to new system (allowing you to still use the old one if need to), and eventually, getting rid of the old system.

Assuming I can figure out how to write to config.py programmatically while the file is loaded- IIRC windows has a problem with that- this isn't that hard, and I'd just need dates for each of the follow ups, since those would all be oneish line changes.

I think for a timeline for it would be something like: "now" (whenever this PR gets merged) for step 1, step 2 would be about a week after documentation gets released, step 3 would be after the documentation has been around a few months... say 3, and step 4 would be another 3-6 months later maybe?

As for the following:
> there are some good stuff and bug fixes in this PR that I would be down to merge, but...

Sure! What do you have in mind? I can probably seperate out whichever changes into a different PR if neccissary. (ps: my original plan for after this PR was merged was pep8 complience, since all the files turn up very green and squiggly in PyCharm)

Thanks for the time you spent reviewing this, and reading this ^-^

**Comment by shanrauf** [comment]
This PR is a bit outdated now (mainly my fault), so I am going to close it. I don't think it's a good idea to merge the features related to changing how the config works because it would cause issues with migrating current Morphman guides and people would not be familiar with the new system. But if you add those optimization and refactoring changes into separate, smaller PRs, then I can merge those (e.x the performance fixes, import fixes, etc)

**Pull request closed without merging**
