### PR TITLE
cli: one simple working command, to dump a MorphMan database

### PR DESCRIPTION
**Pull request by gnprice**
This comes in handy on its own, for pulling out data from MorphMan in
a form that's easy to use one's favorite general-purpose text tools
for reading, searching, comparing against other data, etc.

It also provides a skeleton for further CLI commands that do more
interesting things.

### CODE REVIEW

**Comment by gnprice** [comment]
For a quick preview of the major reason I'm interested in a CLI like this, see [this commit](https://github.com/gnprice/MorphMan/commit/7200b50) and [its successor](https://github.com/gnprice/MorphMan/commit/e4e889b), at the tip of my `master` branch.

**Comment by kaegi** [comment]
I've read your code on master and this is seriously amazing (and all this in two days)!

I also tested the code in this PR, and there are a few nitpicks:
-   the anki folder will only be found on English systems - every other system has a localized `~/Documents` path. I think this is too much of a restriction.
-   it only allows one profile with MorphMan. An easy solution to these two points is a `--profile` or `--db-path` argument, which is mandatory for cases where no default `dbs` path is found.
-   I want to keep the main directory clean, because the "installation" is nothing more than copying and I don't want any "distracting" files for users. That was the reason there was no `.gitignore`, which I didn't remember fast enough (I had a local version which ignored itself, and I might revert to that state). So if possible, `mm` should be moved inside `morph`.

Some additional remarks:
-   The command-line program might benefit from further refactoring, decoupling and reusing MorphMan components. For example I see a great overlap between `main.py:updateNotes()` and your `cmd_next()`. This requires the rating code to be separated from the code that sets the note fields (the function is to big either way).
-   `config.py` only needs Anki to find the profile path. By leaving out the first part of the dbs path, and moving the `join-profile_path-with-dbs`-logic into other parts of the codebase, your `cli.py` could access all settings from `config.py`.

**Comment by gnprice** [comment]
Aw, thanks! :D 

> An easy solution to these two points is a `--profile` or `--db-path` argument, which is mandatory for cases where no default `dbs` path is found.

Sure, good thought. I'll do that.

> I want to keep the main directory clean, because the "installation" is nothing more than copying and I don't want any "distracting" files for users. That was the reason there was no `.gitignore`, which I didn't remember fast enough

Oh huh. I'm a little embarrassed that I'd actually forgotten that that's the normal installation procedure -- in my own install, I have a clone of a Git repo for each of the addons I use, and in my `Anki/addons` folder I've made symbolic links to the relevant files and directories for each addon. (E.g. for MorphMan, this means a symlink to `morphman.py` and another to `morph/`.) Which I took a bit of time to go and set up when I decided I wanted to make changes of more than a line here or there, so that I really wanted to have source control. :-)

I think a setup more like that would be better for Anki users in general, keeping addons more separated from each other and making it easier to upgrade or remove them separately, as well as for addon authors and contributors to do development on them in a way that works very smoothly with sharing them in a place like GitHub. But that requires some changes in Anki -- small ones, perhaps, I think, but nevertheless changes there -- so that doesn't help us here.

I think the right answer, in principle, is that the releases that users download and unpack should contain only the files that the user is actually asked to install. For example, there's already `LICENSE` and `README.md`, which the user already has to ignore; and in the future it would be great for there to be some tests ;-) -- which the user probably also isn't interested in, and in any case if there's a `tests/` directory or something we wouldn't want people to copy that to `Anki/addons/tests/`. 

How do you currently make the releases? I haven't played with the `releases` feature which GitHub provides and I see you're using, so I don't know much about how it works. If there's any kind of support for "binary" releases, it'd be pretty straightforward to have something like a tiny release script (or Makefile) that just copies the relevant few files into a build tree and tars/zips those up.

... But although that should be a good solution for things like `.gitignore` and tests, the point of `mm` is to be there to be used. Definitely cleaner if it doesn't add to the number of top-level paths. I'll move it under `morph`.

OK, that's a long comment I just wrote; I'll hit send and then start replying to your other thoughts.

**Comment by gnprice** [comment]
> The command-line program might benefit from further refactoring, decoupling and reusing MorphMan components. For example I see a great overlap between `main.py:updateNotes()` and your `cmd_next()`. This requires the rating code to be separated from the code that sets the note fields (the function is to big either way).

Agreed on all points!

> `config.py` only needs Anki to find the profile path. By leaving out the first part of the dbs path, and moving the `join-profile_path-with-dbs-logic` into other parts of the codebase, your `cli.py` could access all settings from `config.py`.

Ah, true! We could make all of those settings into relative paths, and that would cut that dependency.

Though actually, the main way most of MorphMan gets at those settings is through `cfg` in `util.py`. The extra work that's doing seems to be mainly about per-deck and per-model overrides. (Tangent question: are those still relevant given the shiny new filter-based configuration that you introduced a little while ago?) In any case, those don't matter in at least most CLI contexts, so I guess it'll be fine to ignore that.

There's also the settings in `jcfg`, but I don't think those will be much harder -- it's just a JSON field in a SQLite database, so we can read the database ourselves.

**Comment by kaegi** [comment]
> How do you currently make the releases? I haven't played with the releases feature which GitHub provides and I see you're using, so I don't know much about how it works. If there's any kind of support for "binary" releases, it'd be pretty straightforward to have something like a tiny release script (or Makefile) that just copies the relevant few files into a build tree and tars/zips those up.

I don't really "use" the releases feature like I do with https://github.com/kaegi/SubtitleMemorize/releases. See there at the bottom of the page: without drafting a "real" release it just shows the tag with an option to download the source code. At that time there I didn't find an easy-to-set-up command line tool that publishes a binary, so I had to login, write the text, drag and drop a file, .... That is a big overhead. For this project I just tag the commit and do a `git push --tags` and am done with it.

> I think the right answer, in principle, is that the releases that users download and unpack should contain only the files that the user is actually asked to install. For example, there's already LICENSE and README.md, which the user already has to ignore; and in the future it would be great for there to be some tests ;-) -- which the user probably also isn't interested in, and in any case if there's a tests/ directory or something we wouldn't want people to copy that to Anki/addons/tests/.

I will look into a more sophisticated way of using the Releases section with [github-release](https://github.com/aktau/github-release).

**Comment by kaegi** [comment]
> Tangent question: are those still relevant given the shiny new filter-based configuration that you introduced a little while ago?

I don't use them but here [here](https://github.com/kaegi/MorphMan/issues/12#issuecomment-274260900) for a use-case (more or less a hack - I'm not sure this is needed with the latest version). Deleting them _should_ be safe, but I'm not sure I'm aware of _all_ consequences.

**Comment by gnprice** [comment]
> At that time there I didn't find an easy-to-set-up command line tool that publishes a binary, so I had to login, write the text, drag and drop a file, .... That is a big overhead. For this project I just tag the commit and do a git push --tags and am done with it.

Yeah, that does sound like a pain -- makes total sense not to want to do that.

> I will look into a more sophisticated way of using the Releases section with github-release, so that these things are possible.

Awesome!

If you find that that tool doesn't quite do what you want or has some annoying rough edges, another option is that the same services like Travis and Appveyor that are handy for automatically running a test suite (and popular and free for open-source projects) seem to also offer the option to upload releases to GitHub: see https://www.appveyor.com/docs/deployment/github/ or https://docs.travis-ci.com/user/deployment/releases/ . Given that we already want to add some tests and therefore probably want to start using one or both of those services, that could be a convenient option too.

**Pull request merged**
