### PR TITLE
Several small changes to cut dependencies on a full running Anki

### PR DESCRIPTION
**Pull request by gnprice**
I have a branch which adds a CLI entry point to MorphMan, which I find very useful. Just built that this weekend, and hoping to get some PRs for it up soon. (It's already in `master` on my fork for anyone curious.)

Part of what makes the CLI so convenient is that it isn't tied to having a full running Anki application around it. That means not importing anything from `aqt`; and the easiest way to accomplish that right now is to avoid importing `morph.util`, which wants to get the Anki application's main window from `aqt.mw` and pull config information off of that. Ideally the CLI would have access to all the configuration in your Anki profile, and I don't think that's fundamentally hard, but as far as I can see it'd require a wider refactoring. Fortunately I've been able to get away without that -- just so long as I can import the `morph.morphemizer` and `morph.morphemes` modules.

So, this branch puts together some small fixes and refactorings that make those modules independent of `aqt` and a running Anki. I think nearly all of it is clearly a strict improvement in the code; the one exception is where I pull `mecab_blacklist` out of configuration and straight into the relevant code. I think that's the right thing too, though, for the reasons in the commit message.

Small logistical note: This branch has three commits that are probably cleanest to leave as separate commits rather than squash-merge. I think GitHub's ["rebase and merge"](https://help.github.com/articles/about-pull-request-merges/#rebase-and-merge-your-pull-request-commits) option is probably ideal; also happy to make three separate PRs or whatever's most convenient for you.

### CODE REVIEW

**Comment by kaegi** [comment]
First of all: thank you! I see great potential in this!

It always was a huge annoyance to fully debug anki with `pdb` if all I wanted was to test some MorphMan functionality (including the need to restart sometimes, select profile, select deck, select cards, ...). Modularization is a really big gain here, so specific functionality can be tested easily. I'm also very open to CLI for database management and other fields, which allows to combine the power of a shell with the helpfulness of MorphMan.

I also see this as a stepping stone for _automated_ tests. I really like python and how fast and easy it is to program in it, but the lack of an enforced type system let's you slip many errors into large codebases. For example in your commit you use `getFilterByTagsAndType` in `newMorphHelper.py` without importing it (I'm currently fixing this locally) - which every statically typed language would have catched  at compile time. Uncoupling major parts of code from Anki means that writing automated tests will get straightforward.

**Comment by kaegi** [comment]
I merged the fixed and rebased commits (which GitHub doesn't seem to recognize). So I'm closing this PR.

**Comment by gnprice** [comment]
Thanks for another fast reply!

Yeah, it would be excellent to start adding some tests. That can go a long way toward being able to easily develop and make changes, because it adds a layer of confidence that you're not breaking something you didn't see and because automated tests can be so much faster than clicking through steps in a GUI to see the effect of a change.

> For example in your commit you use getFilterByTagsAndType in newMorphHelper.py without importing it

Ah, good catch, thanks. :)

Independently of tests, it's also now possible to use static types in Python! See for example [this blog post](http://blog.zulip.org/2016/10/13/static-types-in-python-oh-mypy/), or [this talk](https://www.youtube.com/watch?v=ZP_QV4ccFHQ). Mypy, the Python typechecker described in that post and talk, would have caught that bug. Adding some types to this code would be pretty great too.

Meanwhile, small but while we're looking at that code: do you understand how that `highlight` function gets called? It gets attached to a hook named `fmod_morphHighlight`, but I'm coming up empty looking for where that hook would get invoked.

**Comment by kaegi** [comment]
> Independently of tests, it's also now possible to use static types in Python! See for example this blog post, or this talk. Mypy, the Python typechecker described in that post and talk, would have caught that bug. Adding some types to this code would be pretty great too.

This looks very good. I will look into.

> Meanwhile, small but while we're looking at that code: do you understand how that highlight function gets called? It gets attached to a hook named fmod_morphHighlight, but I'm coming up empty looking for where that hook would get invoked.

The relevant part in Anki is [here](https://github.com/dae/anki/blob/e870468ad653eb60ca9a249907b3d7d8806a4959/anki/template/template.py#L179-L183). Also took me some time to track down the first time (basically everything with `fmod_` is called). You can use it in a card template by writing `{{morphHighlight:Expression}}` instead of `{{Expression}}`.

**Comment by kaegi** [comment]
Also: you need to add coloring information to the `Styling` section:

```
/* A morpheme can be highlighted to point out the words you have to focus on.
Every morpheme will be put into its own span wich has following attributes:
<span class="morphHighlight" mtype="${thisMorphemeMaturityType}" mat="${thisMorphemeMaturity}">
where
thisMorphemeMaturityType is "unknown", "seen", "known" or "mature" and
thisMorphemeMaturity is an integer which is the greatest interval of all cards this morpheme is in. */
[mtype=unknown] { color: red; }
[mtype=seen] { color: orange; }
[mtype=known] { color:green; }
[mtype=mature] { color:blue; }
```

**Comment by gnprice** [comment]
Aha! Cool -- that seems potentially useful.

Is there documentation somewhere for that MorphMan feature? Would be good to write down somewhere to help people find it.

**Pull request closed without merging**
